# Generated by Django 5.2.12 on 2026-04-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_joinrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
